### ISSUE TITLE
About Blank Grabber

### ISSUE THREAD

**Issue by guillaume22222** [Blank-c/Discord-Injection-BG#1]
Hello, im writing this thing because i got an issue on blank grabber. the thung is when i press the "build" button, the part where the programm creates a virtual environment doesn't work. the error message is : error while creating virtual environment.python is unreachable. i tried on differents wifis, differents days and differents options selected, always the same error. Please help me i neef it so much !! i can pay for the answer too if youd like. Thanks and hope that you answer!

**Comment by Blank-c** [comment]
Too late to answer I know, but when asking for solutions, it would be better to attach screenshots.
